#!/usr/bin/env sh
#
# Script to set colors generated by 'wal' a little modified.
# https://github.com/dylanaraps/wal

# Source generated colors.
source "${HOME}/.cache/wal/colors.sh"

# Main function definition.
main() {
    xrdb -merge ~/.cache/wal/rofi.xres &
    killall dunst
    dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "fg" -cf "$fg" -nf "$fg" -fn "ypn envypn 12" -s -lto 3 -nto 5 -cto 0 &
}

# Exection of functions.
main
